version: "3"
services:
  dummy_chat:
    build: .
    environment:
      - FLASK_APP=app.py
    ports:
      - '5000:5000'
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
